### ISSUE TITLE
Computer shuts down upon pressing down arrow

### ISSUE THREAD

**Issue by WolfEdge** [EvanPurkhiser/rEFInd-minimal#16]
Hey man.

Before I start, I'd like to say that personally love this theme for rEFInd. It makes it look great! I found it on Reddit.

Now, about my issue.. When I press the down arrow button (below the OS icons) all I see is the screen flashing black for a very brief moment and then a rectangular, empty terminal window with just a text cursor at the top. My computer then quickly shuts down.

I'm assuming this isn't what is meant to happen. How can I go about correcting it?

I haven't found anything online through searching, sadly. I really would like to take full advantage of this theme so therefore I'd like to get things fully functional.

Any help would be greatly appreciated.

**Comment by EvanPurkhiser** [comment]
I'm glad you like the theme! :-)

The [down arrow](https://github.com/EvanPurkhiser/rEFInd-minimal/blob/master/icons/func_shutdown.png) indeed does shut down the computer. It's part of the minimal aesthetic of this theme (down, representing *shut*down).

You can always toy with displaying more function icons if you'd like, check out #15.

**Comment by WolfEdge** [comment]
Silly me! I had a feeling this was the intended feature (down arrow, bringing the computer down, etc..) but I thought "nah, can't be!" 

Sorry to bring this issue back up but I have a query. Would it bebe possible for me to get the computer to shut down from this icon in a 'cleaner' fashion? So no terminals or flashes or anything, just me pressing Enter and then screen going black and the computer turning off. I figure if I change a few configurations I could get this to happen, but some general guidance would be much appreciated!
