### ISSUE TITLE
Ubuntu GNOME icon

### ISSUE THREAD

**Issue by WolfEdge** [EvanPurkhiser/rEFInd-minimal#17]
Hey,

I think an [Ubuntu GNOME icon](https://ubuntugnome.org/ubuntu-gnome-15-10-is-released/) would be a great addition for people like me who use Ubuntu GNOME opposed to normal (Unity) Ubuntu.

Ubuntu GNOME is an official Ubuntu version that uses GNOME 3 instead of Unity.

**Comment by WolfEdge** [comment]
**UPDATE**

I figured I'd try to make my own icon for it. I'm not very good with graphic design haha. I made [this](http://i.imgur.com/JUoUoeZ.png). It has a transparent background, is 128x128, and the 'black' is the same shade as the other icons. However, it has very sharp edges and generally isn't a very good icon, but I thought I'd try to contribute to my own issue however I could, even if it's just putting forward this icon concept.

**Comment by EvanPurkhiser** [comment]
Oooh, looks good. I'll fix it up and add it in soon :+1:

**Comment by WolfEdge** [comment]
Hey man. Figured I'd try making it again, but I made it properly this time. [I think it looks pretty good](http://i.imgur.com/nNMkPgE.png), worthy of inclusion into your theme maybe? Haha.

This time I used your original Ubuntu icon, kept the circle and positioning that's already there, filled in the circle with the shade of black you use, and used a path from an official Ubuntu GNOME SVG file to make a selection I could fill in with white, and voila, the icon was made. Thoughts? 

![Ubuntu GNOME icon](http://i.imgur.com/nNMkPgE.png)

**Comment by EvanPurkhiser** [comment]
Perfect! Could you open a pull request? :-)

**Comment by WolfEdge** [comment]
Sure but what do I name the icon? `os_ubuntugnome.png`?

**Comment by EvanPurkhiser** [comment]
Sounds good to me. I don't think refind will be able to identify the OS

**Comment by EvanPurkhiser** [comment]
I'm going to go ahead and merge this in myself :-) Thank you!

**Comment by WolfEdge** [comment]
Ahh damn sorry about that! I completely forgot to do the pull request. I remember doing research about what to name the file and whether it would be recognised and so on, but I didn't really get too far and I found the rEFInd docs a tad too complicated for me. It slipped my mind to submit the pull request! Sorry about that.

**Comment by EvanPurkhiser** [comment]
No problem! Thank you again for making the icon!
