### ISSUE TITLE
Background image doesn't fill the background.

### ISSUE THREAD

**Issue by trusktr** [EvanPurkhiser/rEFInd-minimal#18]
I fell in love with the theme at first site, so I gave it a try. It came out like this on my MacBook Pro Retina:

![wp_20160104_02_19_45_pro](https://cloud.githubusercontent.com/assets/297678/12088062/ea225946-b28c-11e5-8856-de9fbd773956.jpg)

Is the retina screen too big? How might we fix it?

**Comment by mrfrankus** [comment]
You need to replace background.jpg with a large image.

**Comment by trusktr** [comment]
I was hoping to just use the theme, not re-make it. Is there a bigger version of that background somewhere?

**Comment by EvanPurkhiser** [comment]
Yep, [checkout the readme](https://github.com/EvanPurkhiser/rEFInd-minimal#background-sizes).

**Comment by theRealPadster** [comment]
The background is available on deviantART, in higher quality (2560x1600).

http://leonardoalanb.deviantart.com/art/Minimalist-wallpaper-295519786
![2560x1600](https://cloud.githubusercontent.com/assets/1565883/8440175/9074a37c-1f3e-11e5-998b-f7abcc57e2f9.jpg)

I use that as my background.png since it fits my 2560x1440 monitor.

**Comment by trusktr** [comment]
Sweet, thanks guys. Even the full-size image is too small, but the `banner_scale fillscreen` setting made it work.

@EvanPurkhiser Do you think including `banner_scale fillscreen` by default would be good? I think a pixelated background would be better than the small unfitted background by default. Plus, that background image isn't the type of image that will look too bad when pixelated anyways since the gradients are subtle.

**Comment by EvanPurkhiser** [comment]
Since enough people have asked I'll go ahead and add in that option!
