### ISSUE TITLE
How to get rid of the hard-disk icons that appear below the main icons?

### ISSUE THREAD

**Issue by trusktr** [EvanPurkhiser/rEFInd-minimal#20]
There are some small hard-disk icons to the bottom right of the main icons. Can we disable those?

![wp_20160104_02_19_45_pro](https://cloud.githubusercontent.com/assets/297678/12088062/ea225946-b28c-11e5-8856-de9fbd773956.jpg)

**Comment by EvanPurkhiser** [comment]
Fixed.
