### ISSUE TITLE
A way to set the default os_linux image?

### ISSUE THREAD

**Issue by trusktr** [EvanPurkhiser/rEFInd-minimal#22]
I was able to replace os_linux.png with the os_arch.png icon. Is there another way to specify the default icon for automatically detected Linux entries (I don't have any manual entries)?

**Comment by WolfEdge** [comment]
If you're trying to change the icon of an automatically detected OS, you can go into this theme's `icons` directory and find the icon file for the specific OS icon you want to change. For example, when I was modifying this theme to make a [custom version](https://github.com/WolfEdge/rEFInd-minimal) I changed the `os_win.png` file to use a different Windows icon which in turn is used instead.

**Comment by trusktr** [comment]
@WolfEdge That's what I did too, but I wasn't sure if there was some other option to specify inside theme.conf as an alternative.

**Comment by DanaGoyette** [comment]
Try setting the filesystem label, using e2label or such.  On my system, direct kernel boot showed just the generic Linux icon.  Once I set the filesystem label to something including "ubuntu", it started using the Ubuntu icon.  I'll bet the same will be true for any other distro icon.

**Comment by chrislondon** [comment]
I was also able to make a custom icon by naming it ".VolumeIcon.png" and placing it in the very top directory of my volume.
