### ISSUE TITLE
Move theme into themes folder instead of root

### ISSUE THREAD

**Issue by lukechilds** [EvanPurkhiser/rEFInd-minimal#24]
I've just built a theme (heavily inspired by yours, great job btw) and to make the installation a bit neater, I'm reccomending people create a `themes` folder and put it in there. It would also allow people to have multiple themes installed, which could be easily switched between, without cluttering up the root rEFInd directory.

I know there's no official right or wrong place to put the theme but I feel like this method is a lot neater. Would you accept a PR to follow this directory pattern on your theme too?

**Comment by WolfEdge** [comment]
Hey mate. 

I don't think this is possible. rEFInd itself controls what directories it looks in and so on. @EvanPurkhiser has just made a theme. I'd recommend the following:

- Asking rEFInd's creator to implement this functionality.
- Mucking about with symlinks or something like that to have a 'current' theme and a folder of alternatives. I'm not sure how you'd do this.
- I think rEFInd is open-source. Perhaps you could try messing around a bit there.

Good luck mate.

**Comment by lukechilds** [comment]
It is possible, it's how my theme currently works. You just need to add `include themes/rEFInd-minimal/theme.conf` to your config instead of `include rEFInd-minimal/theme.conf`.

It would mean people could have multiple themes installed in a `themes` folder without cluttering the root directory and easily switch between them by changing their config from `include themes/theme-1/theme.conf` to `include themes/theme-2/theme.conf`.

Maybe I'm not explaining it very well, I'v added a PR (#25) to demo what changes would be needed, it's a very simple change.

**Comment by WolfEdge** [comment]
Ahh okay. I'm sorry - I misinterpreted you there.

I like your idea. But wouldn't you have the propose this to many other makers of popular themes?

**Comment by lukechilds** [comment]
Yeah, I intend to.

Gotta start somewhere :wink:

**Comment by WolfEdge** [comment]
Good on you mate 😂

**Comment by EvanPurkhiser** [comment]
Let's do it!
