### ISSUE TITLE
Name of linux kernel/images

### ISSUE THREAD

**Issue by sonarforte** [EvanPurkhiser/rEFInd-minimal#28]
How do you have the custom configuration for the kernel and boot image without the version numbers?

I'm currently in manjaro (but I think the same thing applies to arch) and the kernel and image look like this:

`vmlinuz-4.1-x86_64`
`initramfs-4.1-86_64.img`

It's possible to just add those specific names into the refind conf, but this is not very forward compatible.

So the question is, what do I have to do to get those clean, forward compatible names? 

Thanks.

**Comment by EvanPurkhiser** [comment]
[This isn't a problem for Arch Linux](https://git.archlinux.org/svntogit/packages.git/tree/trunk/linux.preset?h=packages/linux#n4).

I think you might have better luck using the auto-detect feature of rEFInd.
