### ISSUE TITLE
Shut downs when hitting Enter on the arrow for more options

### ISSUE THREAD

**Issue by tinchou** [EvanPurkhiser/rEFInd-minimal#30]
Hey,

I just installed this theme, and as the title says, I'm unable to see the "more options" menu when moving to the arrow and hitting Enter. Is there any log I can look up so we can figure this out?

Great theme, thanks!

**Comment by EvanPurkhiser** [comment]
The down arrow isn't for more options unfortunately. It literally does mean shut*down*.

I don't think there's a way in rEFInd to create a sub menu.

**Comment by tinchou** [comment]
Oh... What about the options like "boot to Lenovo Repair tool, boot to memcheck", etc.? I have a row of about seven icons below my main OSes.

I like that they're hidden, but is there any way to access them?

**Comment by EvanPurkhiser** [comment]
For me I don't use those features, so in this theme I've hidden them.

There was some small discussion about adding icons for things like that over in #15 but I haven't gotten around to finding something exactly to my liking.

You would have to petition Roderick to have a feature added to rEFInd that allows the extra options to be hidden away.
