### ISSUE TITLE
rEFInd-minimal theme, won't load.

### ISSUE THREAD

**Issue by HELIX77** [EvanPurkhiser/rEFInd-minimal#34]
Here are screenshots:
what i am i doing wrong here ?
the size of the background is 1280 × 720, i have resized it for my macbook air early 2014
![screen shot 2017-02-13 at 3 29 24 pm](https://cloud.githubusercontent.com/assets/25654133/22903477/bdbc575c-f206-11e6-91a7-fe2d456e91a0.png)
![screen shot 2017-02-13 at 3 31 47 pm](https://cloud.githubusercontent.com/assets/25654133/22903482/bee7e72c-f206-11e6-8db7-bc259bdcdd3e.png)
![screen shot 2017-02-13 at 3 32 45 pm](https://cloud.githubusercontent.com/assets/25654133/22903491/c5eed4cc-f206-11e6-8f59-b5cbbb9e50de.png)

**Comment by Zerophase** [comment]
You missed a keyword. This is what you need: `include themes/rEFInd-minimal/theme.conf`

**Comment by HELIX77** [comment]
Thanks i got it to work !
