### ISSUE TITLE
Add wallpapers for different resolutions

### ISSUE THREAD

**Issue by EvanPurkhiser** [EvanPurkhiser/rEFInd-minimal#4]
Currently the wallpaper included is 1680x1050. It would be good to find the wallpaper in different resolutions for people looking to get the exact same look as the screenshot.

Unfortunalty I [can't seem to find](https://www.google.com/search?tbs=sbi:AMhZZiuoTuxGG_1Wsa5w6dsGFftEY6zDOPRYqT7dSt1TVKWSAm2FNCjrekznW7jPmeG36GrRGAXyVmpGYGucM4BhVxPvNeqPjhgFef0EvQseXVUaKtdykrGwD_1HVbG0GbKCEpbCqwMTBmXZhDDGIYai_1FO5MAxiDIqtY2bVK4LD8XnwFQpoNLFnD4AHzcBMlPjVCbBDqG-I62X1wgIKOlurnt5005tDsmlbIQdM-mhMN1jDOmgH-0DK3whJJKYBsinndsc2wZjfOeER74eyGd402W9a7zxZZmtxwU3_1dyWS9M3fRvo-zowf_1Aeg_1ibYXKYnOa-uisU8KHw8XpXFHawKD6Oyb-MaBLPcGlWrWvTRW8keejtzvv2h4&bih=988&biw=1680) the same wallpaper in any other resolution.

If anyone has any other wallpapers that look similar, or would be a good fit for the theme, let me know!

**Comment by T0m93** [comment]
Hey. There is just Something missing in the Theme.config

Please add this in the Banner Option.

banner_scale fillscreen

It fixes this issue :) 
Sources refind.config or http://www.rodsbooks.com/refind/themes.html
Maybe u should update your source :) By the Way very Nice theme!!!

**Comment by EvanPurkhiser** [comment]
Thanks @T0m93.

I think I'm going to keep the `banner_scale` option left to it's default value for now and leave it up to the user to enable this. I think an upscaled image is worse than a native one, so I'd rather not upscale by default :-)

**Comment by T0m93** [comment]
Ok. But there are 3 possibilities. 
1.The picture is too big ---> doesnt look as nice as it does normally ---> banner_scale fillscreen---> fits and no quality loss
2. Picture fits--> no changes
3. picture too small  --> looks weird. upscaling would fix that ---> Quality loss, but at least it fits the screen and doesnt look weird :) and if it sucks just replace the background.png with whatever you like^^ 

But yout theme, your rules :) By the way it looks really awesome on my Mac, just added some text on it (by the way use Calibre for Text. matches perfect the theme). 
Maybe u should fix/change the win8 icon. Because it uses the default blue one (i just replaced the default win8 icon with your win icon and renamed it).

Have a nice day :)

**Comment by EvanPurkhiser** [comment]
Thanks for the feedback again @T0m93!

Yeah that's true. But I think I'd rather leave that decision up to the user. I'd rather them get an obvious bad experience (image too small / large) and then either replace the image, or settle with using `banner_scale`, than simply add that option and then have the user scratching their head as to why the background looks fuzzy.

> But yout theme, your rules :)

Thanks again man I really appreciate it! :-)

I fixed the windows issue in aa27619. Thanks for letting me know!

**Comment by theRealPadster** [comment]
I was looking for similar wallpapers on deviantART and actually found the original, in higher quality (2560x1600).

http://leonardoalanb.deviantart.com/art/Minimalist-wallpaper-295519786
![2560x1600](https://cloud.githubusercontent.com/assets/1565883/8440175/9074a37c-1f3e-11e5-998b-f7abcc57e2f9.jpg)

**Comment by EvanPurkhiser** [comment]
That's it! Thank you very much @theRealPadster :100:

**Comment by theRealPadster** [comment]
You don't want to replace the version in use with the higher-quality one?

**Comment by EvanPurkhiser** [comment]
I think I'd like for the user to select a background image that is the right size for them. I have 1920x1080 monitors, so I will leave it at that as the default. But I did put a section into the readme about selecting a wallpaper size.

**Comment by T0m93** [comment]
banner_scale fillscreen ? Why not now? Would fix everything. With 2560x1600 wallpaper there shouldn't be any upscaling issues.

**Comment by theRealPadster** [comment]
Yeah, could the 2560x1600 version be included and banner_scale fillscreen be set as default? The pattern doesn't have any details that would be lost if it just centred the image, as it's just a gradient for the most part. For 1080p screens it would fill it (with some cut off around the edges), and on bigger screens, like 1440p, it would still look good, without stretching.
