### ISSUE TITLE
Scaling problem

### ISSUE THREAD

**Issue by 0oMarko0** [EvanPurkhiser/rEFInd-minimal#43]
I got a little scaling problem, the icon appears very big and take much of the space. I've tried to set the banner_scale to noscale and fillscreen but nothing seems to work for me. I got a 1080p monitor if that may help. Is the problem only the background? I've opened it with feh and it fit my screen perfectly.

Thanks you

**Comment by EvanPurkhiser** [comment]
Do other themes have this issue?

**Comment by 0oMarko0** [comment]
Yes I've tried this theme as well: https://github.com/lukechilds/refind-ambience but i may have resolved my problem. I was using a .jpg to test another background I've switch to a .png as stated in the documentation and the scaling is much better now
