### ISSUE TITLE
rEFInd Still Shows Default Theme

### ISSUE THREAD

**Issue by iancbogue** [EvanPurkhiser/rEFInd-minimal#46]
**_I know this has been discussed before, but I'm not sure which advice I should follow._** 
I installed rEFInd, added the theme folder, installed the theme, and updated the refind.conf file with `include themes/minimal/theme.conf`. I changed the name of the folder, so that's why it says minimal instead of rEFInd-minimal. Going off of what was shared in #9, here is my refind.conf: 

[refind.txt](https://github.com/EvanPurkhiser/rEFInd-minimal/files/2386333/refind.txt)

Tree of /boot/efi/EFI/
[tree.txt](https://github.com/EvanPurkhiser/rEFInd-minimal/files/2386334/tree.txt)

I am a newbie to Linux with very little prior experience, so I don't want to go messing with things before I know what to do. If you need anything else, just tell me and I will try to get it.

**Comment by EvanPurkhiser** [comment]
Looks to me like you're doing

```
{
include /minimal/theme.conf
}
```

Which is both not where the file is, and strangely between braces.

It should probably just be 

```
include themes/minimal/theme.conf
```

**Comment by iancbogue** [comment]
So I copied the line from your post, but here's what it looks like when I reboot:

![img_2910](https://user-images.githubusercontent.com/18062067/45913126-c8442300-bde1-11e8-806c-cf0e3437e211.JPG)
So what does this mean and how do I fix it?

**Comment by EvanPurkhiser** [comment]
Case might matter, I see in your `tree.txt` that it's `Minimal` not `minimal`. Can you share your refind.conf again?

**Comment by iancbogue** [comment]
Sure thing. Here is rEFInd.conf as of just now:

[rEFInd.conf](https://pastebin.com/tcUzdC4z)

Would you also like the updated tree? I checked in the themes folder and it appears as if I have changed it from `Minimal` back to `minimal`.

**Comment by EvanPurkhiser** [comment]
Awesome!

**Comment by OctarineSorcerer** [comment]
@iancbogue Would it be possible for you to share your tree/rEFInd.conf that fixed the above screen? I'm having the same issue with another theme (dreary) which is in `refind/themes/refind-dreary`, and have no idea how to debug it.

[tree.txt](https://github.com/EvanPurkhiser/rEFInd-minimal/files/2646600/tree.txt)
[refind.conf](https://github.com/EvanPurkhiser/rEFInd-minimal/files/2646601/refind.conf.txt)

Evan, sorry for adding the issue here - seeing as there's someone who's come across what seems to be the same problem and fixed it, I thought this would be the best place for it.

**Comment by iancbogue** [comment]
@OctarineSorcerer What happened was I rename the folder in which the theme was housed. That caused the configuration .conf file to be confused. Make sure that either you change what the directory is that the .conf file is looking for (there are multiple in the document), or don't rename the folder at all. For example, my theme.conf file says `banner themes/minimal/background.png`. Before, it would have said `banner themes/rEFInd-minimal/background.png`. Does your boot screen look (almost exactly) like mine did? Also, please upload `highres/theme.conf`.

[Updated tree.txt](https://pastebin.com/u9cxhYv8)

**Comment by OctarineSorcerer** [comment]
Ah, I think I see the issue - `highres/theme.conf` uses paths along the lines of `themes/refind-dreary/*.png`, whereas they're actually stored in `themes/refind-dreary/highres/*.png`. I'll edit that to see if changing them to those paths fixes it, and raise an issue there if so. 

Will edit with results, and thank you very much for the help! Don't know why I hadn't looked hard at `highres/theme.conf`.
[highres/theme.conf.txt](https://github.com/EvanPurkhiser/rEFInd-minimal/files/2657248/theme.conf.txt) before those edits.
