### ISSUE TITLE
Show text on hover?

### ISSUE THREAD

**Issue by dylanh724** [EvanPurkhiser/rEFInd-minimal#47]
I have several of the same icons - I'm not sure which is which unless I test them 1-by-1: Even GRUB alt bootloader has the same entry as Ubuntu.

How to show the menu text when hovering over? Minimal is nice, but it's also making me confused ;p

**Comment by EvanPurkhiser** [comment]
As far as I know, this isn't functionality that rEFInd offers.

**Comment by dylanh724** [comment]
> As far as I know, this isn't functionality that rEFInd offers.

The default skin natively uses this ;p I found it in a config file.
