### ISSUE TITLE
Initial screen has no arrow (indicator below icon)

### ISSUE THREAD

**Issue by smalltimer** [evanpurkhiser/rEFInd-minimal#69]
Hi, 

First, thank you for sharing this beautiful theme with the community. I noticed that there is no selection arrow (the small inverted arrow below the OS icon) at the beginning, and it only appears after the user has pressed the arrow-keys on the keyboard. Is this intentional? I find it a bit confusing as you don't know which OS is selected until you touch your machine. 

Thanks!

**Comment by evanpurkhiser** [comment]
This sounds like it may be a bug or new configuration in rEFInd.

Let me know if you're able to resolve, or if anyone else has seen this issue! I'm unfortunately not using rEFInd anymore.

**Comment by smalltimer** [comment]
It was a misconfiguration as I hadn't understood how to specify the 'default' option in rEFInd. Sorry! I'm closing the issue.
