### ISSUE TITLE
Can't get theme to load.

### ISSUE THREAD

**Issue by MQN8R** [EvanPurkhiser/rEFInd-minimal#77]
I have mounted my EFI and created the themes folder, copied the theme in. I added the include themes/rEFInd-minimal/theme.conf as per step 4, however, the theme doesn't load. No doubt my edit of refind.conf is not done correctly.

Would love some help,
Kind regards; 
MQN8R

**Comment by evanpurkhiser** [comment]
Could you share your `refind.conf` file?

Might also be nice to see the `tree` of your EFI mount to make sure everything is in the right place.
